/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as R01Stories00PlaygroundRouteImport } from "./routes/01-stories/00-playground";
import { Route as R01Stories01ActionRouteImport } from "./routes/01-stories/01-action";
import { Route as R01Stories02ActionGroupRouteImport } from "./routes/01-stories/02-action-group";
import { Route as R01Stories03DefaultProvidersRouteImport } from "./routes/01-stories/03-default-providers";
import { Route as R01Stories04DesignWrapperRouteImport } from "./routes/01-stories/04-design-wrapper";
import { Route as R01Stories05ButtonRouteImport } from "./routes/01-stories/05-button";
import { Route as R01Stories06InputRouteImport } from "./routes/01-stories/06-input";
import { Route as R01Stories07LoadingIconRouteImport } from "./routes/01-stories/07-loading-icon";
import { Route as R01Stories08ProseRouteImport } from "./routes/01-stories/08-prose";
import { Route as R01Stories09LoadingBlockRouteImport } from "./routes/01-stories/09-loading-block";
import { Route as R02StylesFrameRouteImport } from "./routes/02-styles/frame";
import { Route as R03AriakitButtonRouteImport } from "./routes/03-ariakit/button";
import { Route as R03AriakitCheckboxRouteImport } from "./routes/03-ariakit/checkbox";
import { Route as R03AriakitSelectRouteImport } from "./routes/03-ariakit/select";
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const R03AriakitSelectRoute = R03AriakitSelectRouteImport.update({
  id: "/03-ariakit/select",
  path: "/03-ariakit/select",
  getParentRoute: () => rootRouteImport,
} as any);
const R03AriakitCheckboxRoute = R03AriakitCheckboxRouteImport.update({
  id: "/03-ariakit/checkbox",
  path: "/03-ariakit/checkbox",
  getParentRoute: () => rootRouteImport,
} as any);
const R03AriakitButtonRoute = R03AriakitButtonRouteImport.update({
  id: "/03-ariakit/button",
  path: "/03-ariakit/button",
  getParentRoute: () => rootRouteImport,
} as any);
const R02StylesFrameRoute = R02StylesFrameRouteImport.update({
  id: "/02-styles/frame",
  path: "/02-styles/frame",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories09LoadingBlockRoute = R01Stories09LoadingBlockRouteImport.update({
  id: "/01-stories/09-loading-block",
  path: "/01-stories/09-loading-block",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories08ProseRoute = R01Stories08ProseRouteImport.update({
  id: "/01-stories/08-prose",
  path: "/01-stories/08-prose",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories07LoadingIconRoute = R01Stories07LoadingIconRouteImport.update({
  id: "/01-stories/07-loading-icon",
  path: "/01-stories/07-loading-icon",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories06InputRoute = R01Stories06InputRouteImport.update({
  id: "/01-stories/06-input",
  path: "/01-stories/06-input",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories05ButtonRoute = R01Stories05ButtonRouteImport.update({
  id: "/01-stories/05-button",
  path: "/01-stories/05-button",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories04DesignWrapperRoute = R01Stories04DesignWrapperRouteImport.update({
  id: "/01-stories/04-design-wrapper",
  path: "/01-stories/04-design-wrapper",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories03DefaultProvidersRoute = R01Stories03DefaultProvidersRouteImport.update({
  id: "/01-stories/03-default-providers",
  path: "/01-stories/03-default-providers",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories02ActionGroupRoute = R01Stories02ActionGroupRouteImport.update({
  id: "/01-stories/02-action-group",
  path: "/01-stories/02-action-group",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories01ActionRoute = R01Stories01ActionRouteImport.update({
  id: "/01-stories/01-action",
  path: "/01-stories/01-action",
  getParentRoute: () => rootRouteImport,
} as any);
const R01Stories00PlaygroundRoute = R01Stories00PlaygroundRouteImport.update({
  id: "/01-stories/00-playground",
  path: "/01-stories/00-playground",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/01-stories/00-playground": typeof R01Stories00PlaygroundRoute;
  "/01-stories/01-action": typeof R01Stories01ActionRoute;
  "/01-stories/02-action-group": typeof R01Stories02ActionGroupRoute;
  "/01-stories/03-default-providers": typeof R01Stories03DefaultProvidersRoute;
  "/01-stories/04-design-wrapper": typeof R01Stories04DesignWrapperRoute;
  "/01-stories/05-button": typeof R01Stories05ButtonRoute;
  "/01-stories/06-input": typeof R01Stories06InputRoute;
  "/01-stories/07-loading-icon": typeof R01Stories07LoadingIconRoute;
  "/01-stories/08-prose": typeof R01Stories08ProseRoute;
  "/01-stories/09-loading-block": typeof R01Stories09LoadingBlockRoute;
  "/02-styles/frame": typeof R02StylesFrameRoute;
  "/03-ariakit/button": typeof R03AriakitButtonRoute;
  "/03-ariakit/checkbox": typeof R03AriakitCheckboxRoute;
  "/03-ariakit/select": typeof R03AriakitSelectRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/01-stories/00-playground": typeof R01Stories00PlaygroundRoute;
  "/01-stories/01-action": typeof R01Stories01ActionRoute;
  "/01-stories/02-action-group": typeof R01Stories02ActionGroupRoute;
  "/01-stories/03-default-providers": typeof R01Stories03DefaultProvidersRoute;
  "/01-stories/04-design-wrapper": typeof R01Stories04DesignWrapperRoute;
  "/01-stories/05-button": typeof R01Stories05ButtonRoute;
  "/01-stories/06-input": typeof R01Stories06InputRoute;
  "/01-stories/07-loading-icon": typeof R01Stories07LoadingIconRoute;
  "/01-stories/08-prose": typeof R01Stories08ProseRoute;
  "/01-stories/09-loading-block": typeof R01Stories09LoadingBlockRoute;
  "/02-styles/frame": typeof R02StylesFrameRoute;
  "/03-ariakit/button": typeof R03AriakitButtonRoute;
  "/03-ariakit/checkbox": typeof R03AriakitCheckboxRoute;
  "/03-ariakit/select": typeof R03AriakitSelectRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/01-stories/00-playground": typeof R01Stories00PlaygroundRoute;
  "/01-stories/01-action": typeof R01Stories01ActionRoute;
  "/01-stories/02-action-group": typeof R01Stories02ActionGroupRoute;
  "/01-stories/03-default-providers": typeof R01Stories03DefaultProvidersRoute;
  "/01-stories/04-design-wrapper": typeof R01Stories04DesignWrapperRoute;
  "/01-stories/05-button": typeof R01Stories05ButtonRoute;
  "/01-stories/06-input": typeof R01Stories06InputRoute;
  "/01-stories/07-loading-icon": typeof R01Stories07LoadingIconRoute;
  "/01-stories/08-prose": typeof R01Stories08ProseRoute;
  "/01-stories/09-loading-block": typeof R01Stories09LoadingBlockRoute;
  "/02-styles/frame": typeof R02StylesFrameRoute;
  "/03-ariakit/button": typeof R03AriakitButtonRoute;
  "/03-ariakit/checkbox": typeof R03AriakitCheckboxRoute;
  "/03-ariakit/select": typeof R03AriakitSelectRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/01-stories/00-playground"
    | "/01-stories/01-action"
    | "/01-stories/02-action-group"
    | "/01-stories/03-default-providers"
    | "/01-stories/04-design-wrapper"
    | "/01-stories/05-button"
    | "/01-stories/06-input"
    | "/01-stories/07-loading-icon"
    | "/01-stories/08-prose"
    | "/01-stories/09-loading-block"
    | "/02-styles/frame"
    | "/03-ariakit/button"
    | "/03-ariakit/checkbox"
    | "/03-ariakit/select";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/01-stories/00-playground"
    | "/01-stories/01-action"
    | "/01-stories/02-action-group"
    | "/01-stories/03-default-providers"
    | "/01-stories/04-design-wrapper"
    | "/01-stories/05-button"
    | "/01-stories/06-input"
    | "/01-stories/07-loading-icon"
    | "/01-stories/08-prose"
    | "/01-stories/09-loading-block"
    | "/02-styles/frame"
    | "/03-ariakit/button"
    | "/03-ariakit/checkbox"
    | "/03-ariakit/select";
  id:
    | "__root__"
    | "/"
    | "/01-stories/00-playground"
    | "/01-stories/01-action"
    | "/01-stories/02-action-group"
    | "/01-stories/03-default-providers"
    | "/01-stories/04-design-wrapper"
    | "/01-stories/05-button"
    | "/01-stories/06-input"
    | "/01-stories/07-loading-icon"
    | "/01-stories/08-prose"
    | "/01-stories/09-loading-block"
    | "/02-styles/frame"
    | "/03-ariakit/button"
    | "/03-ariakit/checkbox"
    | "/03-ariakit/select";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  R01Stories00PlaygroundRoute: typeof R01Stories00PlaygroundRoute;
  R01Stories01ActionRoute: typeof R01Stories01ActionRoute;
  R01Stories02ActionGroupRoute: typeof R01Stories02ActionGroupRoute;
  R01Stories03DefaultProvidersRoute: typeof R01Stories03DefaultProvidersRoute;
  R01Stories04DesignWrapperRoute: typeof R01Stories04DesignWrapperRoute;
  R01Stories05ButtonRoute: typeof R01Stories05ButtonRoute;
  R01Stories06InputRoute: typeof R01Stories06InputRoute;
  R01Stories07LoadingIconRoute: typeof R01Stories07LoadingIconRoute;
  R01Stories08ProseRoute: typeof R01Stories08ProseRoute;
  R01Stories09LoadingBlockRoute: typeof R01Stories09LoadingBlockRoute;
  R02StylesFrameRoute: typeof R02StylesFrameRoute;
  R03AriakitButtonRoute: typeof R03AriakitButtonRoute;
  R03AriakitCheckboxRoute: typeof R03AriakitCheckboxRoute;
  R03AriakitSelectRoute: typeof R03AriakitSelectRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/03-ariakit/select": {
      id: "/03-ariakit/select";
      path: "/03-ariakit/select";
      fullPath: "/03-ariakit/select";
      preLoaderRoute: typeof R03AriakitSelectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/03-ariakit/checkbox": {
      id: "/03-ariakit/checkbox";
      path: "/03-ariakit/checkbox";
      fullPath: "/03-ariakit/checkbox";
      preLoaderRoute: typeof R03AriakitCheckboxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/03-ariakit/button": {
      id: "/03-ariakit/button";
      path: "/03-ariakit/button";
      fullPath: "/03-ariakit/button";
      preLoaderRoute: typeof R03AriakitButtonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/02-styles/frame": {
      id: "/02-styles/frame";
      path: "/02-styles/frame";
      fullPath: "/02-styles/frame";
      preLoaderRoute: typeof R02StylesFrameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/09-loading-block": {
      id: "/01-stories/09-loading-block";
      path: "/01-stories/09-loading-block";
      fullPath: "/01-stories/09-loading-block";
      preLoaderRoute: typeof R01Stories09LoadingBlockRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/08-prose": {
      id: "/01-stories/08-prose";
      path: "/01-stories/08-prose";
      fullPath: "/01-stories/08-prose";
      preLoaderRoute: typeof R01Stories08ProseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/07-loading-icon": {
      id: "/01-stories/07-loading-icon";
      path: "/01-stories/07-loading-icon";
      fullPath: "/01-stories/07-loading-icon";
      preLoaderRoute: typeof R01Stories07LoadingIconRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/06-input": {
      id: "/01-stories/06-input";
      path: "/01-stories/06-input";
      fullPath: "/01-stories/06-input";
      preLoaderRoute: typeof R01Stories06InputRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/05-button": {
      id: "/01-stories/05-button";
      path: "/01-stories/05-button";
      fullPath: "/01-stories/05-button";
      preLoaderRoute: typeof R01Stories05ButtonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/04-design-wrapper": {
      id: "/01-stories/04-design-wrapper";
      path: "/01-stories/04-design-wrapper";
      fullPath: "/01-stories/04-design-wrapper";
      preLoaderRoute: typeof R01Stories04DesignWrapperRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/03-default-providers": {
      id: "/01-stories/03-default-providers";
      path: "/01-stories/03-default-providers";
      fullPath: "/01-stories/03-default-providers";
      preLoaderRoute: typeof R01Stories03DefaultProvidersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/02-action-group": {
      id: "/01-stories/02-action-group";
      path: "/01-stories/02-action-group";
      fullPath: "/01-stories/02-action-group";
      preLoaderRoute: typeof R01Stories02ActionGroupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/01-action": {
      id: "/01-stories/01-action";
      path: "/01-stories/01-action";
      fullPath: "/01-stories/01-action";
      preLoaderRoute: typeof R01Stories01ActionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/01-stories/00-playground": {
      id: "/01-stories/00-playground";
      path: "/01-stories/00-playground";
      fullPath: "/01-stories/00-playground";
      preLoaderRoute: typeof R01Stories00PlaygroundRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R01Stories00PlaygroundRoute: R01Stories00PlaygroundRoute,
  R01Stories01ActionRoute: R01Stories01ActionRoute,
  R01Stories02ActionGroupRoute: R01Stories02ActionGroupRoute,
  R01Stories03DefaultProvidersRoute: R01Stories03DefaultProvidersRoute,
  R01Stories04DesignWrapperRoute: R01Stories04DesignWrapperRoute,
  R01Stories05ButtonRoute: R01Stories05ButtonRoute,
  R01Stories06InputRoute: R01Stories06InputRoute,
  R01Stories07LoadingIconRoute: R01Stories07LoadingIconRoute,
  R01Stories08ProseRoute: R01Stories08ProseRoute,
  R01Stories09LoadingBlockRoute: R01Stories09LoadingBlockRoute,
  R02StylesFrameRoute: R02StylesFrameRoute,
  R03AriakitButtonRoute: R03AriakitButtonRoute,
  R03AriakitCheckboxRoute: R03AriakitCheckboxRoute,
  R03AriakitSelectRoute: R03AriakitSelectRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
