export const DIRECTIONS = [
  {
    direction: "horizontal" as const,
    TopRight: "TopRight",
    BottomRight: "BottomRight",
    TopLeft: "TopLeft",
    BottomLeft: "BottomLeft",
    Right: "Right",
    Left: "Left",
    Top: "Top",
    Bottom: "Bottom",
    right: "right",
    left: "left",
    top: "top",
    bottom: "bottom",
    height: "height",
  },
  {
    direction: "vertical" as const,
    TopRight: "BottomRight",
    BottomRight: "BottomLeft",
    TopLeft: "TopRight",
    BottomLeft: "TopLeft",
    Right: "Bottom",
    Left: "Top",
    Top: "Right",
    Bottom: "Left",
    right: "bottom",
    left: "top",
    top: "right",
    bottom: "left",
    height: "width",
  },
];
